<?php
define('TITLE', 'BAOSTAR.PRO');
define('DON_VI', 'đ');
define('DEFAULT_IMG', 'https://scontent-sin6-2.xx.fbcdn.net/v/t1.6435-9/109764297_600916327228448_3011929643277362470_n.jpg?_nc_cat=105&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=72_ExHmqYBoAX-caZZk&_nc_ht=scontent-sin6-2.xx&oh=856184e0db706cfd37a75bc102a01a77&oe=60B93EFB');

define("DOMAIN_TANG_LIKE_CHEO", env("DOMAIN_TANG_LIKE_CHEO", "https://agency.tanglikecheo.com"));
define("DOMAIN_MFB", env("DOMAIN_MFB", "https://api.mfb.vn"));
define("DOMAIN_AUTOFB_PRO", env("DOMAIN_AUTOFB_PRO", "https://autofb.pro"));
define("DOMAIN_AUTO_LIKE_CC", env("DOMAIN_AUTO_LIKE_CC", "https://agency.autolike.cc"));
define("DOMAIN_VIEW_YT", env("DOMAIN_VIEW_YT", "https://viewyt.com"));
define("DOMAIN_VIEW_NHANH", env("DOMAIN_VIEW_YT", "https://viewsubnhanh.com"));
define("DOMAIN_BUFFVIEWER", env("DOMAIN_BUFFVIEWER", "https://buffviewer.com"));
define('DOMAIN_VNKINGS', 'https://vnkings.net');
define('TANG_LIKE_ORG', 'https://tanglike.org');
define('DOMAIN_TRUM_LIKE_SUB', 'https://trumlikesub.vn');
define('DOMAIN_VIETNAMFB', 'https://vietnamfb.com');
define('DOMAIN_CONGLIKE', 'http://conglike.com');
define('DOMAIN_SUBGIARE', 'https://subgiare.vn');
define('DOMAIN_2FA', 'http://2fa.shop');
define('DOMAIN_FARM', 'https://api.like88.cc');
define('DOMAIN_PRO_YTB', 'https://proytb.info');
define('DOMAIN_1FB', 'https://1fb.vn');
define('DOMAIN_MLIKE', 'https://mlike.vn');
define('DOMAIN_THANHLIKE', 'https://thanhlike.net');
define('DOMAIN_SA_BOM_MO', 'https://customer.sabommo.net');
define('DOMAIN_TRAODOISUB', 'https://traodoisub.com');
define('DOMAIN_BAOSTAR_TOOL', 'https://tool.baostar.pro');
define('DOMAIN_DVO', 'https://app.dichvuonline.vn');
define('DOMAIN_DVST', 'https://dichvust.com/');
define('DOMAIN_MXH2', 'https://2mxh.com');
define('PRICE_PER_REMOVE', 2000);
define('MAX_LIMIT', 101);
